### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by flywire** [pfalcon/ppxml2db#1]
How about a readme and adding a simple example in the wiki?

**Comment by pfalcon** [comment]
> How about a readme

Yeah, definitely need to do that. As soon as I FIRE, I'll be doing only such things, until then, will have to wait its turn :-( .

**Comment by flywire** [comment]
One line for each would work. It could be shorter than your response above.

**Comment by flywire** [comment]
I'm on win10. How is the Makefile used?

**Comment by pfalcon** [comment]
> I'm on win10. How is the Makefile used?

For example, via WSL. But otherwise, it doesn't do anything magic, just runs all *.sql files against a database file. You can do it in any way you find suitable.

**Comment by flywire** [comment]
The README.md is excellent. Thank you.

> You can do it in any way you find suitable.

I'll explore non-WSL options for Windows.
