### ISSUE TITLE
no such table: security

### ISSUE THREAD

**Issue by flywire** [pfalcon/ppxml2db#11]
Startup failure initialising sql. Does not seem to affect execution.

Open PP
* Help, Welcome, Open the Kommer sample file, 
* File, Save As, XML with "ID" attributes, kommer.xml

```
E:\sqlite>test kommer
-- Loading resources from tmp.txt
Error: near line 1: no such table: security

Microsoft Windows [Version 10.0.22631.3880]
Python 3.12.4
ppxml2db.py 1.0
```

E:\sqlite>type test.bat
```
@echo off
if %1!==! goto usage
if exist %1.db del %1.db
if exist tmp.txt del tmp.txt
rem for /f "tokens=*" %%f in (tables.txt) do echo .read %%f.sql >>tmp.txt
for %%f in (*.sql) do echo .read %%~nf.sql >>tmp.txt
sqlite3 -init tmp.txt %1.db .quit
rem del tmp.txt
@echo on
@ver
@python --version
@python ppxml2db.py --version
python ppxml2db.py %1.xml %1.db
python db2ppxml.py %1.db %12.xml
goto end
:usage
@echo off
echo.
echo Usage: %0 filename(without extension)
echo.
:end
```

E:\sqlite>type tmp.txt
```
.read account.sql
.read account_attr.sql
.read attribute_type.sql
.read bookmark.sql
.read config_entry.sql
.read config_set.sql
.read dashboard.sql
.read latest_price.sql
.read price.sql
.read pricedata.sql!.sql
.read property.sql
.read security.sql
.read security_attr.sql
.read security_event.sql
.read security_prop.sql
.read taxonomy.sql
.read taxonomy_assignment.sql
.read taxonomy_category.sql
.read taxonomy_data.sql
.read watchlist.sql
.read watchlist_security.sql
.read xact.sql
.read xact_cross_entry.sql
.read xact_unit.sql
```

**Comment by flywire** [comment]
Error generated by user file in folder: `.read pricedata.sql!.sql`.

Direct Windows support would be useful, including a specific list of required sql files (eg tables.txt).

**Comment by pfalcon** [comment]
> Error generated by user file in folder: .read pricedata.sql!.sql.

Then please close this ticket as invalid (not related to the project itself).

To track files in a project directory (which are changed, which are stray), use the git tool.

> Direct Windows support would be useful, including a specific list of required sql files (eg tables.txt).

There won't any special Windows support, this is a generic project. You're welcome to use any of many available POSIX-like layers for Windows, like Cygwin, MSYS, WSL, etc.

**Comment by flywire** [comment]
A POSIX-like layer to support Windows is an overkill. A trivial change to the following makefile code to use a list of sql files would support a Windows batch file too.

```
TABLES = .account .account_attr \
    .security .security_attr .security_event .security_prop .latest_price .price \
    .watchlist .watchlist_security \
    .xact .xact_unit .xact_cross_entry \
    .taxonomy .taxonomy_category .taxonomy_assignment .taxonomy_data \
    .dashboard \
    .property \
    .bookmark .attribute_type .config_set .config_entry
```

**Comment by pfalcon** [comment]
I'm closing this as the original reported issue was a user error. If there're other topics worth recording here, please open a separate ticket with clear naming and description.
