### ISSUE TITLE
Wish to Santa Clause: Let me not just edit the line, but "copy it to a new item"

### ISSUE THREAD

**Issue by MichaelMeier99** [pfalcon/ppxml2db#3]
Please look at the screenshot, where it would be useful to copy an existing dividend into a new booking line and THEN edit it.

In other words where is now
- edit the booking

it would be great to have 2 items
- edit the booking
- copy the booking in to a new one and edit it.
![copyAccountLine](https://github.com/pfalcon/ppxml2db/assets/49785471/f5b6c7b9-b5b1-43a3-b33d-6b4abec34474)

**Comment by pfalcon** [comment]
Wrong project?

**Comment by MichaelMeier99** [comment]
thank you!

**Comment by MichaelMeier99** [comment]
thank you for the hint
