### ISSUE TITLE
db2ppxml.py Format Fails in Windows

### ISSUE THREAD

**Issue by flywire** [pfalcon/ppxml2db#5]
```
E:\sqlite>python db2ppxml.py dax.db >dax.xml.out
```

dax.xml
```
      <isRetired>false</isRetired>
      <name>Deutsche Börse AG</name>
          <security reference="../../../../../securities/security[30]"/>
```

dax.xml.out
```
      <isRetired>0</isRetired>
      <name>Deutsche Börse AG</name>
          <security reference="..\..\..\..\..\securities\security[30]"/>
```

**Comment by flywire** [comment]
![image](https://github.com/pfalcon/ppxml2db/assets/11288701/39313e84-805a-49ba-8bf3-530d4228bec5)

**Comment by pfalcon** [comment]
> "..\..\..\..\..\securities\security[30]"

I just pushed a fix for that, please confirm that it helped.

Will look into the boolean issue as time permits.

Not seeing any issues with "extended" (non-ASCII?) chars in your quote, can you elaborate?

**Comment by flywire** [comment]
It might just be a np++ (editor) font display issue:

![image](https://github.com/pfalcon/ppxml2db/assets/11288701/b986ab88-d633-41eb-9cd4-f9e5bab8b475)

I'm configured Windows English (Australia) US keyboard

**Comment by pfalcon** [comment]
>       <isRetired>0</isRetired>

Really cannot see what may be wrong here, it's explicitly converted to bool: https://github.com/pfalcon/ppxml2db/blob/master/db2ppxml.py#L163 . Make sure you use the latest version of the repo (git pull).

**Comment by flywire** [comment]
> I just pushed a fix for that, please confirm that it helped.

No, identical output generated.

> cannot see what may be wrong here, it's explicitly converted to bool

Just something I saw, no worries.

**Comment by pfalcon** [comment]
> No, identical output generated.

Gotcha. Please update with `git pull --rebase`.

**Comment by flywire** [comment]
Hmm, I've been slack. I just copied raw then overwrote py file in folder. I downloaded zip then and overwrote all folder files to check again but same result. Fairly certain a library is overwriting that mod in Windows.

**Comment by flywire** [comment]
I did a manual replace `\` with `/` and the file opens but the German character set is not displaying properly in the new file.

**Comment by pfalcon** [comment]
> I did a manual replace \ with / and the file opens

Yeah, but it would be nice if you confirmed that it's fixed in the tool itself, because you'd need to do it again and again.

**Comment by pfalcon** [comment]
Regarding encoding issues: those are likely Windows peculiarities (of not using UTF-8 encoding consistently). I have an idea how it might be possible to address that, but that would be much more blind-folded than e.g. backslashes issue, so I would need more input from you:

1. What exact Windows version do you use?
2. Run following in Python3 interactive prompt:
```
>>> import sys
>>> sys.stdout.encoding
'utf-8'
```
(The output above is for Linux).
3. Please attach both source dax.xml which you use and output from db2ppxml.py.

**Comment by flywire** [comment]
* Windows 11 Pro Version 23H2 OS build 22631.3737 [*](https://forum.portfolio-performance.info/t/ppxml2db-import-export-portfolioperformance-xml-file-to-from-database/28839/6)
*
```
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.stdout.encoding
'utf-8'
```
* https://forum.portfolio-performance.info/uploads/short-url/8pvo9Q3khyM6I3fenmFR5m14NlD.zip [dax2.xml](https://github.com/user-attachments/files/15996331/dax2.xml.txt)

**Comment by flywire** [comment]
Seems the encoding issue is about local Code Page: https://stackoverflow.com/questions/16083916/the-encoding-that-notepad-just-calls-ansi-does-anyone-know-what-to-call-it

Anyway, it is less of an issue than #4

**Comment by flywire** [comment]
Fixing the file shows the difference, [dax2.zip](https://github.com/user-attachments/files/16038395/dax2.zip) [dax3.zip](https://github.com/user-attachments/files/16038396/dax3.zip) `0xF6` becomes `0xC3B6` :

![image](https://github.com/pfalcon/ppxml2db/assets/11288701/18a04528-9934-4654-a6bf-4c918a1734a6)

**Comment by pfalcon** [comment]
> Fixing the file shows the difference, [dax2.zip](https://github.com/user-attachments/files/16038395/dax2.zip) [dax3.zip](https://github.com/user-attachments/files/16038396/dax3.zip) 0xF6 becomes 0xC3B6 :

If that's the case, it's problem with your source file and not ppxml2db tools. XML files must have UTF-8 encoding, while your input file doesn't. Where did you get it from? dax.xml I "downloaded" from inside of PP application is properly utf-8 encoded, but I did that on Linux. Given that dax.xml was removed from PP, I dug it out in git history, and see that it's utf-8 encoded as expected. So, you'd need to check your processing chain for that file to see what might have changed its encoding (theoretically, you can suspect PP for saving file in non-utf8 encoding on Windows, but there's such a low chance for that, but feel free to reproduce).

**Comment by flywire** [comment]
> Where did you get it from?

I assume _it_ refers to dax.db, generated by linux: https://forum.portfolio-performance.info/t/ppxml2db-import-export-portfolioperformance-xml-file-to-from-database/28839/12 which I used in Windows with db2ppxml.py to generate dax2.xml. 

I've demonstrated twice ([1](https://github.com/pfalcon/ppxml2db/issues/5#issuecomment-2192654064) and [2](https://github.com/pfalcon/ppxml2db/issues/5#issuecomment-2197826782)) that UTF-8 is the default python on my system. It seems to be more like a Code Page issue to me. Regardless, it is not a big issue to me because those characters aren't used in Australia.

**Comment by pfalcon** [comment]
> I assume it refers to dax.db, generated by linux

This gets only more and more confusing. Let's start from the beginning. And as dax.xml is no longer available in recent PPs, let's switch to kommer.xml instead. Here's a kind of response I'd like to get from you when ask "where did you get that file?". Yes, it takes a bit more effort and time, but that's the only way to have progress, instead of wasting time in circles:

1. Start Portfolio Performance 0.69.0.
2. On the "Welcome" page, click "Open the Kommer sample file"
3. The sample file will open in a new tab. Save it using "XML" under "kommer.xml" name.
4. The "kommer.xml" has size 505248 bytes and md5sum of `780b4e07b1a048073eab63a8dadd86e5`.

Proof that kommer.xml still contains non-ASCII chars:

```
$ grep --color='auto' -P -n "[\x80-\xFF]" kommer.xml
5163:                    <name>St. Barthélemy</name>
$
```

(Yes, only one, but should be enough.)

I also note that ppxml2db couldn't deal properly with this latest version of kommer.xml after recent changes pushed to it. Ok, fixed and changes pushed to the repo.

For reference, I also attach kommer.xml file, zipped, here.
[kommer.zip](https://github.com/user-attachments/files/16040291/kommer.zip)

**Comment by pfalcon** [comment]
> I've demonstrated twice (https://github.com/pfalcon/ppxml2db/issues/5#issuecomment-2192654064 and https://github.com/pfalcon/ppxml2db/issues/5#issuecomment-2197826782) that UTF-8 is the default in python on my system. 

Yes. What I could do is to explicitly read/write XML as utf-8, but I don't see how that would help in your case, and you already seems to have utf-8 *even for console*.

> Regardless, it is not a big issue to me because those characters aren't used in Australia.

Well, it's just by a chance I'm working on #7, and have window to look into related issues. Once I've done, I unlikely will look at ppxml2db anytime soon, so I'd rather handle reasonably possible issues now.


> It seems to be more like a Code Page issue to me. Regardless, it is not a big issue to me because those characters aren't used in Australia.

**Comment by pfalcon** [comment]
> Well, it's just by a chance I'm working on https://github.com/pfalcon/ppxml2db/issues/7, and have window to look into related issues. Once I've done, I unlikely will look at ppxml2db anytime soon, so I'd rather handle reasonably possible issues now.

Well, given this, it makes sense to just fix that and call it done. Pushed to repo. If you use `db2ppxml.py in.db out.xml` (note: not `>redirect.xml`), it will explicitly write file with UTF-8 encoding.

**Comment by flywire** [comment]
> use `db2ppxml.py in.db out.xml` (note: not `>redirect.xml`), it will explicitly write file with UTF-8 encoding.

Fixed.

I can't generate a `*.db` file so I tested with the same dax.db from the [PP forum](https://github.com/pfalcon/ppxml2db/issues/5#issuecomment-2192682614).
