### ISSUE TITLE
ANN: Switching to XML format with "id" attribute

### ISSUE THREAD

**Issue by pfalcon** [pfalcon/ppxml2db#7]
I've been using ppxml2db every day since the project was started, though "using" is a bit of misnomer, as I was suffering thru it. Due to known deficiencies in PP XML format, https://github.com/portfolio-performance/portfolio/issues/3417, import is very resource-intensive and slow, so it's a pain to run it any time. So, I've grown to make my experiments in https://github.com/portfolio-performance/portfolio/issues/3417 into production-ready code and switch to use the new XML format afterwards. The specific plan is:

1. Contribute the required changes to PortfolioPerformance. Well, post the pull request to be specific.
2. Update ppxml2db for new format.
3. Stop supporting old format (no changes / no bug reports processed).

Usefulness of this for other parties depends on p.1, and of course I don't have control over whether my contribution will be accepted, in what way, and in which timeframe. So, just posting as a disclosure of future plans.

**Comment by pfalcon** [comment]
@flywire : FYI

**Comment by flywire** [comment]
> 1. Contribute the required changes to PortfolioPerformance. Well, post the pull request to be specific.

Excellent!

**Comment by pfalcon** [comment]
Upstream patch is posted: https://github.com/portfolio-performance/portfolio/pull/4117

**Comment by pfalcon** [comment]
https://github.com/portfolio-performance/portfolio/pull/4117 was merged, and PP 0.70.0 was released with this change. I intend to switch to supporting only the new XML format as the next step.

**Comment by pfalcon** [comment]
With v1.0, just pushed to the repo, the project switched to XML-id format.

**Comment by flywire** [comment]
Great. xml file is so much easier to understand.
